# 1. ベースイメージを選択:
FROM selenium/standalone-edge:126.0

# FROM selenium/standalone-edge:latest
# FROM selenium/standalone-chrome:latest

# 2. 作業ディレクトリを設定:
WORKDIR ${SELENIUM_SHARED}

# 3. 環境変数を設定:    
ENV PYTHONIOENCODING=utf-8
ENV TZ="Asia/Tokyo"
ENV LANG=ja_JP.UTF-8
ENV LANGUAGE=ja_JP:ja
